Implemented codegen for CTL record fix changes
mlabs-haskell/purescript-bridge pull request #18
Opened 2022-05-04 04:50 UTC by gnumonik

This branch contains the codegen tools needed for the CTL record fix updates (WIP)

2022-05-06 18:40 UTC, bladyjoker commented
@gnumonik please fix the build and notify us when it's done so we can review this.

2022-05-06 18:55 UTC, bladyjoker requested changes
Please add tests where you compare against Haskell BuiltinData reps. Make sure to test `newtypes` and `records`

2022-05-11 06:18 UTC, gnumonik commented
@bladyjoker need your help fixing the IPC so I don't have to literally run all the tests by hand. 

there's a lingering JSON issue with newtype records that we need to fix. 

but the stupid manual tests pass and that means this PR is just about done

2022-05-12 18:41 UTC, bladyjoker commented on test/RoundTrip/app/src/Main.purs
> +          log $ show (toData testData)
FIXME: THe json roundtrip test hangs here

2022-05-13 19:33 UTC, bladyjoker commented
@gnumonik 

```
Round trip tests (Purescript <-> Haskell)
  Round trip prerequisite tests
    `[test/RoundTrip/app] $ spago build` should work [✔]
    `[test/RoundTrip/app] $ spago build` should not warn of unused packages buildable [✔]
  with defaultBridge
    should have a Purescript process running [✔]
    should produce Aeson-compatible representations [✔]    
      +++ OK, passed 100 tests.
  with ledger bridge
    should have a Purescript process running [✔]
    should produce PlutusData compatible representations [✔]    
      +++ OK, passed 100 tests.

Finished in 2.9049 seconds
6 examples, 0 failures
```

2022-05-13 19:36 UTC, bladyjoker commented
TODO:
- [ ] Resolve Argonaut vs PlutusTx integer conflict (Argonaut doesn't handle Integers, and PlutusTx doesn't handle Ints)
   - **STATUS**: Vladimir is trying to make CTL use Aeson solely so we can print into that?
- [ ] Specify Arbitrary for PlutusTx.AssocMap
- [ ] Embed plutus-ledger-api types into testing types

2022-05-17 11:35 UTC, bladyjoker approved these changes

2022-05-17 11:36 UTC, bladyjoker commented
CI build is still broken, keeping it that way until I find a solution

2022-05-17 11:37 UTC, merged